### ISSUE TITLE
libebvdi.so cannot be found

### ISSUE THREAD

**Issue by sjoerdmullender** [hadess/displaylink-rpm#2]
I compiled and installed the latest displaylink driver using this package (I built the RPM myself using the provided sources), but the driver didn't work.  My external monitory wasn't found.  I then asked about this problem on the displaylink forum and got a very helpful reply.  See [1].
Per the reply I modified the spec file and added a line to the %install section:
cp evdi-%{version}/library/libevdi.so $RPM_BUILD_ROOT/usr/libexec/displaylink
With this change, the driver works and finds my external monitor.
(For a complete change, the comment about not copying libevdi.so should also be removed.)

[1] http://www.displaylink.org/forum/showthread.php?p=80215

**Comment by hadess** [comment]
And thanks for testing again :)

Let me know if there's any more problems.

**Comment by sjoerdmullender** [comment]
This version works.  Thanks.
